"use client";

import { useState, useTransition } from "react";
import { AlertTriangle, CheckCircle2, ChevronRight, Circle, Clock3 } from "lucide-react";
import { Button } from "@/components/ui/LegacyButton";
import { Card, CardBody, CardHeader } from "@/components/ui/LegacyCard";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { toast } from "@/lib/toast";
import { setEngagementStageAction } from "@/lib/actions/engagement-workflow";
import { formatDate, titleCase } from "@/lib/utils";

export type FrozenWorkflow = { id:string;workflow_name:string;workflow_version:number;current_stage_key:string|null;status:string;applied_at:string };
export type FrozenStage = { id:string;stage_key:string;label:string;phase:string;description:string|null;sort_order:number;stage_kind:string;status:string;entered_at:string|null;completed_at:string|null;client_visible_label:string|null;is_client_visible:boolean };
export type AllowedTransition = { stageKey:string;label:string;transitionLabel:string|null;requiresReason:boolean;kind:string };
export type ProgressTracker = { intake_status:string;documents_status:string;engagement_letter_status:string;payment_status:string;signature_status:string;extension_status:string;filing_status:string;review_status:string;updated_at:string };
export type EngagementDeadline = { id:string;jurisdiction:string;deadline_type:string;due_on:string;label:string;source:string;is_active:boolean;is_satisfied:boolean };

const progressLabels: Record<string,string>={intake_status:"Intake",documents_status:"Documents",engagement_letter_status:"Engagement letter",payment_status:"Payment",signature_status:"Signature",extension_status:"Extension",filing_status:"Filing",review_status:"Review"};
function tone(value:string):"neutral"|"info"|"warning"|"success"|"danger" { if(["complete","completed","accepted","approved","paid","signed","filed","not_required"].some(word=>value.includes(word)))return "success";if(["missing","failed","rejected","overdue"].some(word=>value.includes(word)))return "danger";if(["pending","requested","waiting","invoiced","assigned","sent"].some(word=>value.includes(word)))return "warning";return "neutral"; }

export function ProductionWorkflowPanel({ engagementId,workflow,stages,transitions,progress,deadlines,canAdvance }: { engagementId:string;workflow:FrozenWorkflow;stages:FrozenStage[];transitions:AllowedTransition[];progress:ProgressTracker|null;deadlines:EngagementDeadline[];canAdvance:boolean }) {
  const [selected,setSelected]=useState<AllowedTransition|null>(null);const [reason,setReason]=useState("");const [pending,start]=useTransition();
  const current=stages.find(stage=>stage.status==="current"); const phases=Array.from(new Set(stages.filter(stage=>stage.stage_kind==="standard").map(stage=>stage.phase)));
  const move=()=>{if(!selected)return;if(selected.requiresReason&&!reason.trim()){toast.error("A reason is required for this transition.");return;}start(async()=>{const result=await setEngagementStageAction({engagementId,stageKey:selected.stageKey,reason});if(result.error)toast.error(result.error);else{toast.success(result.success!);setSelected(null);setReason("");}});};
  return <div className="space-y-6">
    <Card><CardHeader><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-semibold">{workflow.workflow_name}</h2><p className="text-xs text-muted">Frozen version {workflow.workflow_version} · applied {formatDate(workflow.applied_at)}</p></div><StatusBadge label={current?.label??"No current stage"} tone="info"/></div></CardHeader><CardBody className="space-y-5">
      <div className="flex gap-2 overflow-x-auto pb-2">{phases.map(phase=>{const phaseStages=stages.filter(stage=>stage.phase===phase&&stage.stage_kind==="standard");const done=phaseStages.length>0&&phaseStages.every(stage=>stage.status==="completed");const active=phaseStages.some(stage=>stage.status==="current");return <div key={phase} className={`min-w-36 rounded-lg border px-3 py-2 ${active?"border-accent-400 bg-accent-50":done?"border-accent-200 bg-white":"border-border bg-slate-50"}`}><p className="text-xs font-medium">{titleCase(phase)}</p><p className="mt-1 text-xs text-muted">{done?"Complete":active?"Current phase":`${phaseStages.filter(s=>s.status==="completed").length}/${phaseStages.length} stages`}</p></div>;})}</div>
      {current&&<div className="rounded-xl border border-accent-200 bg-accent-50 p-4"><p className="text-xs font-medium uppercase tracking-wide text-accent-700">Current production stage</p><h3 className="mt-1 font-semibold">{current.label}</h3>{current.description&&<p className="mt-1 text-sm text-muted">{current.description}</p>}<p className="mt-2 text-xs text-muted">Entered {formatDate(current.entered_at)}</p></div>}
      {canAdvance&&<div><p className="mb-2 text-sm font-medium">Allowed next actions</p><div className="flex flex-wrap gap-2">{transitions.map(item=><Button key={item.stageKey} size="sm" variant={item.kind==="exception"?"danger":"secondary"} onClick={()=>setSelected(item)}>{item.transitionLabel||item.label}<ChevronRight className="size-3.5"/></Button>)}{!transitions.length&&<p className="text-sm text-muted">No outgoing transition is currently available.</p>}</div></div>}
    </CardBody></Card>

      <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><h2 className="text-sm font-semibold">Separate progress trackers</h2></CardHeader><CardBody>{progress?<div className="grid gap-3 sm:grid-cols-2">{Object.entries(progressLabels).map(([key,label])=>{const value=progress[key as keyof ProgressTracker] as string;return <div key={key} className="flex items-center justify-between gap-2 rounded-lg border border-border p-3"><span className="text-sm">{label}</span><StatusBadge label={titleCase(value)} tone={tone(value)}/></div>;})}</div>:<p className="text-sm text-muted">No progress tracker is attached.</p>}</CardBody></Card><Card><CardHeader><h2 className="text-sm font-semibold">Statutory deadlines</h2></CardHeader><CardBody className="space-y-3">{deadlines.filter(d=>d.is_active).map(deadline=><div key={deadline.id} className="flex items-center justify-between gap-3 border-b border-border pb-3"><div><p className="text-sm font-medium">{deadline.label || `${deadline.jurisdiction} · ${titleCase(deadline.deadline_type)}`}</p><p className="text-xs text-muted">{titleCase(deadline.source)}</p></div><div className="text-right"><p className="text-sm font-semibold">{formatDate(deadline.due_on)}</p><StatusBadge label={deadline.is_satisfied?"Satisfied":"Active"} tone={deadline.is_satisfied?"success":"warning"}/></div></div>)}{!deadlines.some(d=>d.is_active)&&<p className="text-sm text-muted">No active statutory deadlines.</p>}<p className="flex items-start gap-2 text-xs text-muted"><Clock3 className="mt-0.5 size-3.5 shrink-0"/>Extensions change filing dates only. Original payment deadlines remain active.</p></CardBody></Card></div>

    <Card><CardHeader><h2 className="text-sm font-semibold">Stage history</h2></CardHeader><CardBody><div className="space-y-2">{stages.map(stage=><div key={stage.id} className={`flex items-start gap-3 rounded-lg px-2 py-2 ${stage.status==="current"?"bg-accent-50":""}`}>{stage.status==="completed"?<CheckCircle2 className="mt-0.5 size-4 text-accent-600"/>:stage.status==="current"?<Clock3 className="mt-0.5 size-4 text-blue-600"/>:stage.stage_kind==="exception"?<AlertTriangle className="mt-0.5 size-4 text-amber-500"/>:<Circle className="mt-0.5 size-4 text-slate-300"/>}<div><p className="text-sm font-medium">{stage.label}</p><p className="text-xs text-muted">{titleCase(stage.phase)} · {titleCase(stage.status)}</p></div></div>)}</div></CardBody></Card>

    <Dialog open={Boolean(selected)} onOpenChange={value=>!value&&setSelected(null)}><DialogContent><DialogHeader><DialogTitle>{selected?.transitionLabel||selected?.label}</DialogTitle></DialogHeader><div className="space-y-4"><p className="text-sm text-muted">Move this engagement from <strong>{current?.label}</strong> to <strong>{selected?.label}</strong>. Verexa will record the change in engagement activity.</p><div className="space-y-1"><Label htmlFor="stageReason">Reason {selected?.requiresReason?"(required)":"(optional)"}</Label><Textarea id="stageReason" value={reason} onChange={event=>setReason(event.target.value)} placeholder="Explain the transition when needed."/></div><div className="flex justify-end gap-2"><Button variant="secondary" onClick={()=>setSelected(null)}>Cancel</Button><Button disabled={pending} onClick={move}>{pending?"Updating…":"Confirm stage change"}</Button></div></div></DialogContent></Dialog>
  </div>;
}
