"use client";

import Link from "next/link";
import { useMemo, useState, useTransition } from "react";
import { Calculator, CircleDollarSign, FileCheck2, Plus, Power, Send, TimerOff } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "@/components/ui/toaster";
import { createPricingAssessmentAction, expireQuoteAction, savePricingConfigurationAction, savePricingRuleAction, saveQuoteAction, sendQuoteAction, setPricingRuleActiveAction } from "@/lib/actions/pricing";
import { formatCurrency, formatDate } from "@/lib/formatters";
import type { Json } from "@/types/database";

export type PricingPerson = { id: string; label: string; kind: "client" | "lead" };
export type PricingPackage = { id: string; name: string; pricing_method: string; pricing_config: Json };
export type PricingRule = { id: string; engagement_type_setting_id: string; name: string; description: string | null; condition: Json; adjustment_type: string; amount: number | null; amount_max: number | null; sort_order: number; is_active: boolean };
export type AssessmentSummary = { id: string; client_id: string | null; lead_id: string | null; status: string; recommended_min: number | null; recommended_max: number | null; recommended_price: number | null; created_at: string; client: { first_name: string | null; last_name: string | null; company: string | null } | null; lead: { first_name: string; last_name: string; company: string | null } | null };
export type QuoteSummary = { id: string; client_id: string | null; pricing_assessment_id: string | null; quote_number: string; quote_type: string; pricing_method: string; amount: number | null; amount_min: number | null; amount_max: number | null; status: string; valid_until: string | null; created_at: string; client: { first_name: string | null; last_name: string | null; company: string | null } | null };

type Permissions = { assess: boolean; rules: boolean; createQuote: boolean; editQuote: boolean; sendQuote: boolean };
const fields = ["filing_status","tax_years","states","w2_count","dependent_count","has_self_employment","rental_count","has_investments_crypto","business_entity_count","is_prior_or_amended","needs_bookkeeping_cleanup"];
const fieldLabels: Record<string,string> = { filing_status:"Filing status",tax_years:"Tax years",states:"State returns",w2_count:"W-2 count",dependent_count:"Dependents",has_self_employment:"Self-employment",rental_count:"Rental properties",has_investments_crypto:"Investments / crypto",business_entity_count:"Businesses owned",is_prior_or_amended:"Prior-year / amended",needs_bookkeeping_cleanup:"Bookkeeping cleanup" };

function name(person: AssessmentSummary["client"] | AssessmentSummary["lead"]) {
  return person?.company || `${person?.first_name ?? ""} ${person?.last_name ?? ""}`.trim() || "Unknown";
}
function configNumber(config: Json, key: string) { return config && typeof config === "object" && !Array.isArray(config) && typeof config[key] === "number" ? config[key] : 0; }

export function PricingWorkspace({ packages, people, rules, assessments, quotes, permissions }: { packages: PricingPackage[]; people: PricingPerson[]; rules: PricingRule[]; assessments: AssessmentSummary[]; quotes: QuoteSummary[]; permissions: Permissions }) {
  const [tab, setTab] = useState<"assessments"|"quotes"|"rules">("assessments");
  const [dialog, setDialog] = useState<"assessment"|"quote"|"rule"|"config"|null>(null);
  const [selectedAssessment, setSelectedAssessment] = useState<AssessmentSummary | null>(null);
  const [selectedPackage, setSelectedPackage] = useState(packages[0]?.id ?? "");
  const [pending, startTransition] = useTransition();
  const packageRules = useMemo(() => rules.filter((rule) => rule.engagement_type_setting_id === selectedPackage), [rules, selectedPackage]);
  const run = (action: () => Promise<{ error?: string; success?: string }>) => startTransition(async () => {
    const result = await action();
    if (result.error) toast.error(result.error);
    else toast.success(result.success ?? "Saved.");
  });

  return <div className="space-y-6">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-semibold tracking-tight">Pricing & Quotes</h1><p className="mt-1 text-sm text-muted">Calculate a short assessment, review the recommendation, and send a client-ready quote before the full organizer.</p></div><div className="flex flex-wrap gap-2">{permissions.assess && <Button variant="brand" onClick={() => setDialog("assessment")}><Calculator className="size-4" /> New assessment</Button>}{permissions.createQuote && <Button variant="outline" onClick={() => { setSelectedAssessment(null); setDialog("quote"); }}><Plus className="size-4" /> New quote</Button>}</div></div>
    <div className="grid gap-3 sm:grid-cols-3"><Metric icon={Calculator} label="Assessments" value={assessments.length}/><Metric icon={CircleDollarSign} label="Open quotes" value={quotes.filter(q => ["draft","sent","viewed"].includes(q.status)).length}/><Metric icon={FileCheck2} label="Accepted" value={quotes.filter(q => q.status === "accepted").length}/></div>
    <div className="flex gap-1 border-b border-border">{(["assessments","quotes","rules"] as const).map(value => <button key={value} onClick={() => setTab(value)} className={`px-4 py-2 text-sm font-medium capitalize ${tab===value ? "border-b-2 border-accent-600 text-accent-700" : "text-muted"}`}>{value}</button>)}</div>

    {tab === "assessments" && <div className="space-y-3">{assessments.map(item => <Card key={item.id}><CardContent className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{name(item.client ?? item.lead)}</p><p className="text-xs text-muted">Calculated {formatDate(item.created_at)} · {item.status}</p></div><div className="flex items-center gap-4"><div className="text-right"><p className="text-xs text-muted">Recommendation</p><p className="font-semibold">{item.recommended_min !== item.recommended_max ? `${formatCurrency(item.recommended_min ?? 0)}–${formatCurrency(item.recommended_max ?? 0)}` : formatCurrency(item.recommended_price ?? 0)}</p></div>{permissions.createQuote && <Button size="sm" variant="outline" onClick={() => { setSelectedAssessment(item); setDialog("quote"); }}>Create quote</Button>}</div></CardContent></Card>)}{!assessments.length && <Empty title="No pricing assessments" text="Start with the two-minute assessment to calculate a consistent recommendation." />}</div>}

    {tab === "quotes" && <div className="space-y-3">{quotes.map(item => <Card key={item.id}><CardContent className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><Link href={`/quotes/${item.id}`} className="font-medium text-accent-700 hover:underline">{item.quote_number}</Link><Badge variant={item.status === "accepted" ? "success" : item.status === "declined" || item.status === "expired" ? "destructive" : "secondary"}>{item.status}</Badge>{item.quote_type === "change_order" && <Badge variant="warning">Change order</Badge>}</div><p className="mt-1 text-xs text-muted">{name(item.client)} · valid through {formatDate(item.valid_until)}</p></div><div className="flex items-center gap-2"><span className="mr-2 font-semibold">{item.amount != null ? formatCurrency(item.amount) : `${formatCurrency(item.amount_min ?? 0)}–${formatCurrency(item.amount_max ?? 0)}`}</span>{permissions.sendQuote && item.status === "draft" && <Button size="sm" variant="brand" disabled={pending} onClick={() => run(() => sendQuoteAction(item.id))}><Send className="size-3.5" /> Send</Button>}{permissions.sendQuote && ["draft","sent","viewed"].includes(item.status) && <Button size="sm" variant="outline" disabled={pending} onClick={() => run(() => expireQuoteAction(item.id))}><TimerOff className="size-3.5" /> Expire</Button>}</div></CardContent></Card>)}{!quotes.length && <Empty title="No quotes" text="Create a quote from a completed pricing assessment or enter one manually." />}</div>}

    {tab === "rules" && <div className="space-y-4"><div className="flex flex-col gap-3 rounded-xl border border-border bg-white p-4 sm:flex-row sm:items-end sm:justify-between"><div className="min-w-64 space-y-1"><Label>Service package</Label><Select value={selectedPackage} onValueChange={setSelectedPackage}><SelectTrigger><SelectValue placeholder="Choose package"/></SelectTrigger><SelectContent>{packages.map(pkg => <SelectItem key={pkg.id} value={pkg.id}>{pkg.name}</SelectItem>)}</SelectContent></Select></div>{permissions.rules && <div className="flex gap-2"><Button variant="outline" onClick={() => setDialog("config")}>Base pricing</Button><Button variant="brand" onClick={() => setDialog("rule")}><Plus className="size-4"/> Add rule</Button></div>}</div>{packageRules.map(rule => <Card key={rule.id} className={!rule.is_active ? "opacity-60" : ""}><CardContent className="flex items-center justify-between gap-3 p-4"><div><div className="flex items-center gap-2"><p className="font-medium">{rule.name}</p><Badge variant={rule.is_active ? "success" : "muted"}>{rule.is_active ? "Active" : "Inactive"}</Badge></div><p className="mt-1 text-xs text-muted">{rule.adjustment_type.replaceAll("_"," ")} · {formatCurrency(rule.amount ?? 0)}{rule.amount_max != null ? `–${formatCurrency(rule.amount_max)}` : ""}</p></div>{permissions.rules && <Button size="sm" variant="outline" onClick={() => run(() => setPricingRuleActiveAction(rule.id,!rule.is_active))}><Power className="size-3.5"/> {rule.is_active ? "Deactivate" : "Activate"}</Button>}</CardContent></Card>)}{!packageRules.length && <Empty title="No rules for this package" text="Set base pricing, then add only the complexity adjustments this service needs." />}</div>}

    <AssessmentDialog open={dialog==="assessment"} onClose={() => setDialog(null)} people={people} packages={packages}/>
    <QuoteDialog open={dialog==="quote"} onClose={() => setDialog(null)} people={people.filter(p=>p.kind==="client")} assessment={selectedAssessment}/>
    <RuleDialog open={dialog==="rule"} onClose={() => setDialog(null)} packageId={selectedPackage}/>
    <ConfigDialog open={dialog==="config"} onClose={() => setDialog(null)} pkg={packages.find(p=>p.id===selectedPackage) ?? null}/>
  </div>;
}

function Metric({ icon: Icon,label,value }: { icon: typeof Calculator; label:string; value:number }) { return <Card><CardContent className="flex items-center gap-3 p-4"><div className="rounded-lg bg-accent-50 p-2 text-accent-700"><Icon className="size-5"/></div><div><p className="text-2xl font-semibold">{value}</p><p className="text-xs text-muted">{label}</p></div></CardContent></Card>; }
function Empty({ title,text }: { title:string;text:string }) { return <div className="rounded-xl border border-dashed border-border bg-white p-10 text-center"><p className="font-medium">{title}</p><p className="mt-1 text-sm text-muted">{text}</p></div>; }
function Field({ name,label,type="text",defaultValue }: { name:string;label:string;type?:string;defaultValue?:string|number;placeholderFix?:string }) { return <div className="space-y-1"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type={type} defaultValue={defaultValue}/></div>; }

function AssessmentDialog({ open,onClose,people,packages }: { open:boolean;onClose:()=>void;people:PricingPerson[];packages:PricingPackage[] }) { const [pending,start]=useTransition(); const [error,setError]=useState<string|null>(null); return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>Quick pricing assessment</DialogTitle></DialogHeader><form className="space-y-4" onSubmit={e=>{e.preventDefault();setError(null);const fd=new FormData(e.currentTarget);const person=people.find(p=>p.id===fd.get("personId"));const answers:Record<string,Json>={};for(const key of fields){const value=fd.get(key);answers[key]=["w2_count","dependent_count","rental_count","business_entity_count"].includes(key)?Number(value||0):String(value??"");}start(async()=>{const result=await createPricingAssessmentAction({clientId:person?.kind==="client"?person.id:undefined,leadId:person?.kind==="lead"?person.id:undefined,packageId:String(fd.get("packageId")),answers});if(result.error)setError(result.error);else{toast.success(result.success!);onClose();}});}}>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-danger">{error}</p>}<div className="grid gap-3 sm:grid-cols-2"><NativeSelect name="personId" label="Lead or client" options={people.map(p=>[p.id,`${p.label} (${p.kind})`])}/><NativeSelect name="packageId" label="Service package" options={packages.map(p=>[p.id,p.name])}/></div><div className="grid gap-3 sm:grid-cols-2"><NativeSelect name="filing_status" label="Expected filing status" options={[["single","Single"],["married_filing_jointly","Married filing jointly"],["head_of_household","Head of household"],["business","Business return"]]}/><Field name="tax_years" label="Tax year(s)" defaultValue={new Date().getFullYear()}/><Field name="states" label="State return(s)" placeholderFix=""/><Field name="w2_count" label="Number of W-2s" type="number" defaultValue={0}/><Field name="dependent_count" label="Number of dependents" type="number" defaultValue={0}/><Field name="rental_count" label="Rental properties" type="number" defaultValue={0}/><Field name="business_entity_count" label="Businesses owned" type="number" defaultValue={0}/>{["has_self_employment","has_investments_crypto","is_prior_or_amended","needs_bookkeeping_cleanup"].map(key=><NativeSelect key={key} name={key} label={fieldLabels[key]} options={[["false","No"],["true","Yes"]]}/>)}</div><div className="flex justify-end"><Button type="submit" variant="brand" disabled={pending}>{pending?"Calculating…":"Calculate assessment"}</Button></div></form></DialogContent></Dialog>; }

function QuoteDialog({ open,onClose,people,assessment }: { open:boolean;onClose:()=>void;people:PricingPerson[];assessment:AssessmentSummary|null }) { const [pending,start]=useTransition();const [error,setError]=useState<string|null>(null); const defaultClient=assessment?.client_id??""; return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent><DialogHeader><DialogTitle>Create draft quote</DialogTitle></DialogHeader><form className="space-y-4" onSubmit={e=>{e.preventDefault();setError(null);const fd=new FormData(e.currentTarget);start(async()=>{const method=String(fd.get("pricingMethod"));const result=await saveQuoteAction({assessmentId:assessment?.id,clientId:String(fd.get("clientId")),pricingMethod:method,amount:method==="range"?undefined:Number(fd.get("amount")||0),amountMin:method==="range"?Number(fd.get("amountMin")||0):undefined,amountMax:method==="range"?Number(fd.get("amountMax")||0):undefined,description:String(fd.get("description")),validUntil:String(fd.get("validUntil")||"")});if(result.error)setError(result.error);else{toast.success(result.success!);onClose();}});}}>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-danger">{error}</p>}<NativeSelect name="clientId" label="Client" defaultValue={defaultClient} options={people.map(p=>[p.id,p.label])}/><NativeSelect name="pricingMethod" label="Quote type" defaultValue={assessment?.recommended_min!==assessment?.recommended_max?"range":"fixed"} options={[["fixed","Fixed price"],["starting_at","Starting at"],["range","Estimated range"],["custom","Custom"],["rule_based","Rule-based"]]}/><div className="grid gap-3 sm:grid-cols-3"><Field name="amount" label="Final / starting amount" type="number" defaultValue={assessment?.recommended_price??0}/><Field name="amountMin" label="Range minimum" type="number" defaultValue={assessment?.recommended_min??0}/><Field name="amountMax" label="Range maximum" type="number" defaultValue={assessment?.recommended_max??0}/></div><Field name="validUntil" label="Valid until" type="date"/><div className="space-y-1"><Label>Description / scope</Label><Textarea name="description" defaultValue="Tax preparation services based on the completed pricing assessment." required/></div><div className="flex justify-end"><Button type="submit" variant="brand" disabled={pending}>{pending?"Saving…":"Create draft"}</Button></div></form></DialogContent></Dialog>; }

function RuleDialog({ open,onClose,packageId }: { open:boolean;onClose:()=>void;packageId:string }) { const [pending,start]=useTransition();const [error,setError]=useState<string|null>(null);return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent><DialogHeader><DialogTitle>Add pricing rule</DialogTitle></DialogHeader><form className="space-y-4" onSubmit={e=>{e.preventDefault();setError(null);const fd=new FormData(e.currentTarget);start(async()=>{const result=await savePricingRuleAction({packageId,name:String(fd.get("name")),description:String(fd.get("description")||""),field:String(fd.get("field")),operator:String(fd.get("operator")),value:String(fd.get("value")||""),adjustmentType:String(fd.get("adjustmentType")),amount:Number(fd.get("amount")||0),amountMax:Number(fd.get("amountMax")||0),sortOrder:Number(fd.get("sortOrder")||0)});if(result.error)setError(result.error);else{toast.success(result.success!);onClose();}});}}>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-danger">{error}</p>}<Field name="name" label="Rule name"/><Field name="description" label="Description"/><div className="grid gap-3 sm:grid-cols-3"><NativeSelect name="field" label="Assessment field" options={fields.map(k=>[k,fieldLabels[k]])}/><NativeSelect name="operator" label="Condition" options={[["equals","Equals"],["greater_than","Greater than"],["greater_than_or_equal","At least"],["is_not_empty","Is not empty"]]}/><Field name="value" label="Value"/></div><div className="grid gap-3 sm:grid-cols-3"><NativeSelect name="adjustmentType" label="Adjustment" options={[["fixed_amount","Add amount"],["per_item","Amount per item"],["percentage","Percentage"],["minimum","Minimum"],["maximum","Maximum"],["price_range","Price range"]]}/><Field name="amount" label="Amount / minimum" type="number"/><Field name="amountMax" label="Maximum (range only)" type="number"/></div><Field name="sortOrder" label="Order" type="number" defaultValue={10}/><div className="flex justify-end"><Button type="submit" variant="brand" disabled={pending}>{pending?"Saving…":"Save rule"}</Button></div></form></DialogContent></Dialog>; }

function ConfigDialog({ open,onClose,pkg }: { open:boolean;onClose:()=>void;pkg:PricingPackage|null }) { const [pending,start]=useTransition();const [error,setError]=useState<string|null>(null); if(!pkg)return null;return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent><DialogHeader><DialogTitle>Base pricing · {pkg.name}</DialogTitle></DialogHeader><form className="space-y-4" onSubmit={e=>{e.preventDefault();setError(null);const fd=new FormData(e.currentTarget);start(async()=>{const result=await savePricingConfigurationAction({packageId:pkg.id,pricingMethod:String(fd.get("pricingMethod")),basePrice:Number(fd.get("basePrice")||0),minimum:Number(fd.get("minimum")||0),maximum:Number(fd.get("maximum")||0)});if(result.error)setError(result.error);else{toast.success(result.success!);onClose();}});}}>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-danger">{error}</p>}<NativeSelect name="pricingMethod" label="Pricing method" defaultValue={pkg.pricing_method} options={[["fixed","Fixed"],["starting_at","Starting at"],["range","Range"],["staff_entered","Staff entered"],["rule_based","Rule based"]]}/><div className="grid gap-3 sm:grid-cols-3"><Field name="basePrice" label="Base / starting price" type="number" defaultValue={configNumber(pkg.pricing_config,"fixed_amount")||configNumber(pkg.pricing_config,"starting_at")}/><Field name="minimum" label="Minimum" type="number" defaultValue={configNumber(pkg.pricing_config,"minimum")}/><Field name="maximum" label="Maximum" type="number" defaultValue={configNumber(pkg.pricing_config,"maximum")}/></div><div className="flex justify-end"><Button type="submit" variant="brand" disabled={pending}>{pending?"Saving…":"Save pricing"}</Button></div></form></DialogContent></Dialog>; }

function NativeSelect({ name,label,options,defaultValue }: { name:string;label:string;options:string[][];defaultValue?:string }) { return <div className="space-y-1"><Label htmlFor={name}>{label}</Label><select id={name} name={name} defaultValue={defaultValue} required className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm">{options.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></div>; }
