import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/EmptyState";
import { Card, CardBody } from "@/components/ui/LegacyCard";
import { Briefcase, Home, Receipt } from "lucide-react";
import { formatCurrency, formatDate } from "@/lib/formatters";

export type ClientEngagementSummary={id:string;engagement_number:string|null;title:string;tax_year:number|null;status:string;updated_at:string};
export type ClientQuoteSummary={id:string;quote_number:string;quote_type:string;status:string;amount:number|null;amount_min:number|null;amount_max:number|null;created_at:string};
export type ClientHouseholdSummary={id:string;household_id:string;relationship:string;household:{household_name:string}|null};

export function ClientEngagementsTab({items}:{items:ClientEngagementSummary[]}){return items.length?<Card><div className="divide-y divide-border">{items.map(item=><Link key={item.id} href={`/engagements/${item.id}`} className="flex items-center justify-between gap-4 p-4 hover:bg-muted/40"><div><p className="font-medium">{item.engagement_number||item.title}</p><p className="text-xs text-muted">{item.tax_year||"No year"} · Updated {formatDate(item.updated_at)}</p></div><Badge variant="secondary">{item.status.replaceAll("_"," ")}</Badge></Link>)}</div></Card>:<EmptyState icon={Briefcase} title="No engagements" description="Create an engagement when the client is ready to begin service."/>}
export function ClientQuotesTab({items}:{items:ClientQuoteSummary[]}){return items.length?<Card><div className="divide-y divide-border">{items.map(item=><Link key={item.id} href={`/quotes/${item.id}`} className="flex items-center justify-between gap-4 p-4 hover:bg-muted/40"><div><p className="font-medium">{item.quote_number}</p><p className="text-xs text-muted">{item.quote_type.replaceAll("_"," ")} · {formatDate(item.created_at)}</p></div><div className="text-right"><p className="font-semibold">{item.amount!=null?formatCurrency(item.amount):`${formatCurrency(item.amount_min)}–${formatCurrency(item.amount_max)}`}</p><Badge variant="secondary">{item.status}</Badge></div></Link>)}</div></Card>:<EmptyState icon={Receipt} title="No quotes" description="Pricing assessments and quotes for this client will appear here."/>}
export function ClientRelationshipGroupsTab({items}:{items:ClientHouseholdSummary[]}){return <div className="space-y-4">{items.length?<Card><div className="divide-y divide-border">{items.map(item=><Link key={item.id} href={`/households/${item.household_id}`} className="flex items-center justify-between p-4 hover:bg-muted/40"><div><p className="font-medium">{item.household?.household_name||"Household group"}</p><p className="text-xs text-muted">Relationship: {item.relationship}</p></div><Badge variant="secondary">Family group</Badge></Link>)}</div></Card>:<EmptyState icon={Home} title="Not linked to a household" description="Households group related individual client records without merging them."/>}<Card><CardBody><p className="text-sm text-muted">Dependents who are not clients can remain household members. A spouse or adult with their own services should have an Individual client record linked to the same group.</p><Link href="/households" className="mt-3 inline-block text-sm font-semibold text-accent-700 hover:underline">Manage household groups</Link></CardBody></Card></div>}
